<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Events\PastCreated;
use App\Models\Past;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

final class PastTest extends TestCase
{
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_can_store_past(): void
    {
        Event::fake([
            PastCreated::class,
        ]);

        $past = new Past;

        $past->encrypted = $this->faker->sha256;
        $past->setExpireFromPeriode('1w');

        $past->save();

        $this->assertTrue($past->wasRecentlyCreated);
    }
}
