name: Deploy to prod
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo_mysql, bcmath, soap, intl
      - name: Install Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-suggest --no-scripts
      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: setup environment
        env:
          GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\n" > ~/.ssh/config
          ./vendor/bin/envoy run deploy --commit="$GITHUB_SHA"
